### Fetch Client Code For Login Request
GET http://clientweb1:password1@localhost:5000/client_code HTTP/1.1

### Open Login Link in New Tab with Client Code
GET http://localhost:5000/login?client_code=m7RzM8dM HTTP/1.1

### Fetch the Token When Authentication is sucessfull
GET http://localhost:5000/token?client_code=m7Q3W0Rq HTTP/1.1

### Fetch the details of a Vehicle with id
GET http://localhost:5000/vehicles/7309863303 HTTP/1.1

### Search for a vehicle with search_key = 'che'
GET http://localhost:5000/vehicles?uid=1707668084&filters_bound=false HTTP/1.1

### Search for a vehicle with search_key = 'che' and odometer max 25000
GET http://localhost:5000/vehicles?sk=che&odo_max=25000 HTTP/1.1

### Search for a vehicle with search_key = 'che' and odometer max 25000 with fuel type gas
GET http://localhost:5000/vehicles?sk=che&odo_max=25000&fuel_types=gas HTTP/1.1